const OTP_EXPIRY_MINUTES = 10;
const OTP_COOLDOWN_MS = 60 * 1000;
const OTP_COOLDOWN_SECONDS = Math.ceil(OTP_COOLDOWN_MS / 1000);

module.exports = {
	OTP_EXPIRY_MINUTES,
	OTP_COOLDOWN_MS,
	OTP_COOLDOWN_SECONDS,
};
